import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Kalnia } from "next/font/google";
import { ThemeProvider } from "@/lib/ThemeContext";
import { ThemeUpdater } from "@/lib/ThemeUpdater";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional
  variable: "--font-inter",
});

const kalnia = Kalnia({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional
  variable: "--font-kalnia",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${kalnia.variable} antialiased min-h-screen flex flex-col`}>
        <ThemeProvider>
          <ThemeUpdater />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
